### ISSUE TITLE
'warn Package d3 has been ignored because it contains invalid configuration'

### ISSUE THREAD

**Issue by robindunkerley** [friyiajr/D3LineChartSample#2]
Hi,

Im trying to follow the article you wrote with the boilerplate. I have followed all the steps for install in the readme.
After starting the react-native server and then running 'npx react-native run-ios' I am receiving the error 'warn Package d3 has been ignored because it contains invalid configuration'.

Any tips on how solve this?

Thanks

**Comment by friyiajr** [comment]
Unfortunately I haven't seen this myself. The only thing I can think of trying is to make sure to use `yarn`. Sometimes there are weird differences between setting up projects with `yarn` vs `npm`. I use `yarn` in all my projects.
